# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lucas Farris
email: lucas@farris.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Data Scientist, Software Engineer. Machine Learning Engineering, ETL, Data Warehousing, Research, Data Visualization. AWS, Google Cloud, kubernetes, helm, python, redshift, postgreSQL, sqlalchemy,flask, scikit-learn, tensorflow, pytorch, pandas, docker, behave, coverage, pytest, Elasticsearch, Fastlane, Jenkins, Java, Adobe XD.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "farris.com.br" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: luksfarris
github_username: luksfarris

repository: luksfarris/luksfarris.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-spaceship

# header_pages:
#   - posts.md

sass:
    sass_dir: _sass

jekyll-spaceship:
   mermaid-processor:
    config:
      theme: 'base'
      themeVariables:
        primaryTextColor: '#fff'
        secondaryTextColor: '#fff'
        tertiaryTextColor: '#fff'
        primaryBorderColor: '#fff'
        secondaryBorderColor: '#fff'
        tertiaryBorderColor: '#fff'
        lineColor: '#fff'
        background: '#0b58a8'
        primaryColor: '#0b58a8'
        secondaryColor: '#0b58a8'
        tertiaryColor: '#0b58a8'
        mainBkg: '#0b58a8'
        # Changing the font makes the container width not get calculated correctly
        # fontFamily: 'Verdana'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
